config/routes.rb
Taskcheck::Application.routes.draw do
  get "welcome/index"

  resources :groups do
    resources :tasks do
      resources :comments
      resources :notes
    end
  end

  resources :user_statuses
  resources :statuses
  devise_for :users
  resources :users

  root :to => 'welcome#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :status
  belongs_to :group
  belongs_to :user
  has_many :comments
  has_many :notes

  def self.task_qty(group_id)
    @lcl_tasks = Task.where("group_id=?", group_id)
    @lcl_tasks.length.to_s

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @group = Group.where("id=?",params[:group_id]).first
    @tasks = Task.where("group_id=?",params[:group_id])
    @all_user_groups = Group.where("user_id=?",current_user[:id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @group = Group.where("id=?",params[:group_id])
    @status_array = Status.all.map{|status| [status.name, status.id] }
    @title = 'Добавить новую задачу в группу '+ @group.first[:name]
    @btn_lbl = 'Создать'
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @group = Group.where("id=?",params[:group_id])
    @title = 'Редактировать задачу в группе '+ @group.first[:name]
    @btn_lbl = 'Редактировать'
    @status_array = Status.all.map{|status| [status.name, status.id] }
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @group_task_params = task_params
    @group_task_params[:group_id] = params[:group_id]
    @task = Task.new(@group_task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to group_tasks_path(params[:group_id]), notice: 'Задача успешно создана.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to group_tasks_path(params[:group_id]), notice: 'Задача успешно обновлена.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to group_tasks_path(params[:group_id]) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :note, :status_id, :group_id, :duration, :deadline, :commit)
    end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
    <legend><%= @title %></legend>
    <% if @task.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
            <ul>
                <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

  <div class="form-group">
    <%= @frm.label :name, "Наименование", style:"display:inline-block",class:"col-lg-2" %>
    <%= @frm.text_field :name, style:"display:inline-block", class:"col-lg-3" %>
  </div>
  <div class="form-group">
    <%= @frm.label :note, "Описание", style:"display:inline-block",class:"col-lg-2"  %>
    <%= @frm.text_area :note, rows: 6, style:"display:inline-block", class:"col-lg-3" %>
  </div>
  <div class="form-group">
    <%= @frm.label :status_id, "Статус", style:"display:inline-block",class:"col-lg-2"  %>
    <%= @frm.select :status_id, @status_array, style:"display:inline-block", class:"col-lg-3" %>
  </div>
  <div class="form-group">
    <%= @frm.label :duration, "Длительность, мин.", style:"display:inline-block",class:"col-lg-2"  %>
    <%= @frm.number_field :duration, style:"display:inline-block", class:"col-lg-3" %>
  </div>
  <div class="form-group">
    <%= @frm.label :deadline, "Крайний срок", style:"display:inline-block",class:"col-lg-2",formats:"%Y.%m.%d"  %>
    <%= @frm.text_field :deadline,
        :value => (@task.deadline.blank? ? '' : @task.deadline.strftime('%d.%m.%Y')),
        style:"display:inline-block", class:"col-lg-1 date-fld" %>
  </div>
  <div class="actions">
    <%= @frm.submit @btn_lbl, class:"btn btn-info"%>
  </div>

app/views/tasks/edit.html.erb
<%= form_for @task, as: :task, url:group_task_path(params[:group_id], @task), html: { class:"bs-example form-horizontal"} do |f|%>

    <% @frm = f%>
    <%= render partial:"form", locals: {title: @title, btn_lbl:@btn_lbl, frm:@frm} %>

<% end %>

<%= link_to 'К списку задач', group_tasks_path(params[:group_id]) %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="span2">
      <legend>Группы</legend>
      <ul class="list-group" style="list-style: none; margin: 2px 0 0;">
      <% @all_user_groups.each do |user_group| %>
          <% @my_text_4_link = '<li class="list-group-item"><span class="badge">'.html_safe+
                  Task.task_qty(user_group.id)+
                  '</span>'.html_safe+
                  user_group.name+
                  '</li>'.html_safe %>
          <%= link_to @my_text_4_link, group_tasks_path(user_group.id) %> </li>
      <% end %>
      </ul>
      <br>
      <%= link_to 'Новая группа', new_group_path, class: "btn btn-info"%>
      <br/><br/>
      <%= link_to 'Ред. группу '+ @group[:name], edit_group_path(params[:group_id]), class: "btn btn-info"%>
    </div>
    <div class="span7">
        <legend>Список задач</legend>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Наименование</th>
                    <th>Описание</th>
                    <th>Статус</th>
                    <th>Время выполнения</th>
                    <th>Срок</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @tasks.each do |task| %>
                    <tr>
                        <td><%= task.name %></td>
                        <td><%= task.note %></td>
                        <td><%= Status.find(task.status_id).name  %></td>
                        <td><%= task.duration %></td>
                        <td><%= task.deadline.blank? ? "": task.deadline.strftime('%d.%m.%Y') %></td>
                        <td><%= link_to 'Открыть', group_task_path(params[:group_id], task), class: "btn btn-mini"%></td>
                        <td><%= link_to 'Редактировать', edit_group_task_path(params[:group_id], task), class: "btn btn-mini btn-info" %></td>
                        <td><%= link_to 'Удалить', group_task_path(params[:group_id], task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= link_to 'Новая задача', new_group_task_path, class: "btn btn-info"%>
    </div>
    <div class="span2">
        <legend>Статусы</legend>
        <div class="list-group">
            <% Status.all.each do |st|%>
                <li class="list-group-item"><span class="badge">0</span><%= st.name %></li>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= form_for @task, as: :task, url:group_tasks_path(params[:group_id], @task), html: { class:"bs-example form-horizontal"} do |f|%>
    <% @frm = f %>
    <%= render partial:"form", locals: {title: @title, btn_lbl:@btn_lbl, frm:@frm} %>
<% end %>
<%= link_to 'К списку задач', group_tasks_path(params[:group_id]) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @task.note %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @task.group_id %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_group_task_path(params[:group_id], @task) %> |
<%= link_to 'Back', group_tasks_path(params[:group_id]) %>