config/routes.rb
Taskcheck::Application.routes.draw do
  get "welcome/index"

  resources :groups do
    resources :tasks do
      resources :comments
      resources :notes
    end
  end

  resources :user_statuses
  resources :statuses
  devise_for :users
  resources :users

  root :to => 'welcome#index'

end

app/controllers/user_statuses_controller.rb
class UserStatusesController < ApplicationController
  before_action :set_user_status, only: [:show, :edit, :update, :destroy]

  # GET /user_statuses
  # GET /user_statuses.json
  def index
    @user_statuses = UserStatus.all
  end

  # GET /user_statuses/1
  # GET /user_statuses/1.json
  def show
  end

  # GET /user_statuses/new
  def new
    @user_status = UserStatus.new
  end

  # GET /user_statuses/1/edit
  def edit
  end

  # POST /user_statuses
  # POST /user_statuses.json
  def create
    @user_status = UserStatus.new(user_status_params)

    respond_to do |format|
      if @user_status.save
        format.html { redirect_to @user_status, notice: 'User status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_statuses/1
  # PATCH/PUT /user_statuses/1.json
  def update
    respond_to do |format|
      if @user_status.update(user_status_params)
        format.html { redirect_to @user_status, notice: 'User status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_statuses/1
  # DELETE /user_statuses/1.json
  def destroy
    @user_status.destroy
    respond_to do |format|
      format.html { redirect_to user_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_status
      @user_status = UserStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_status_params
      params.require(:user_status).permit(:name, :order_num, :user_id)
    end
end

app/helpers/user_statuses_helper.rb
module UserStatusesHelper
end

app/views/user_statuses/_form.html.erb
<%= form_for(@user_status) do |f| %>
  <% if @user_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_status.errors.count, "error") %> prohibited this user_status from being saved:</h2>

      <ul>
      <% @user_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order_num %><br>
    <%= f.number_field :order_num %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_statuses/edit.html.erb
<h1>Editing user_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_status %> |
<%= link_to 'Back', user_statuses_path %>

app/views/user_statuses/index.html.erb
<h1>Listing user_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order num</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_statuses.each do |user_status| %>
      <tr>
        <td><%= user_status.name %></td>
        <td><%= user_status.order_num %></td>
        <td><%= user_status.user_id %></td>
        <td><%= link_to 'Show', user_status %></td>
        <td><%= link_to 'Edit', edit_user_status_path(user_status) %></td>
        <td><%= link_to 'Destroy', user_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User status', new_user_status_path %>

app/views/user_statuses/new.html.erb
<h1>New user_status</h1>

<%= render 'form' %>

<%= link_to 'Back', user_statuses_path %>

app/views/user_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_status.name %>
</p>

<p>
  <strong>Order num:</strong>
  <%= @user_status.order_num %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_status.user_id %>
</p>

<%= link_to 'Edit', edit_user_status_path(@user_status) %> |
<%= link_to 'Back', user_statuses_path %>